language: cpp
dist: trusty
compiler:
- gcc
- clang
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
#- sudo add-apt-repository --yes ppa:boost-latest/ppa
- sudo apt-get --yes update
install:
- sudo apt-get --yes install build-essential wget cmake
#- sudo apt-get --yes install libboost-all-dev
- sudo apt-get --yes install libboost1.55-all-dev
- if test "$CC" == "gcc"; then
    sudo apt-get --yes install gcc-4.9 g++-4.9 &&
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9 &&
    sudo update-alternatives --auto gcc &&
    gcc --version;
  fi
- if test "$CC" == "clang"; then
    sudo apt-get --yes install libc++-dev;
  fi
before_script:
- src_dir=$(pwd)
- build_dir=$(mktemp --directory) 
script:
- cmake -H$src_dir -B$build_dir
- cmake --build $build_dir --target all
after_success:
- cmake --build $build_dir --target test
